<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <AssemblyName>Net.BITKit.Multiplayer.LiteNetLib</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Src/LiteNetLib/**/*.cs" />
    <ProjectReference Include="BITKit.Multiplayer.csproj" />
    <PackageReference Include="LiteNetLib" Version="1.3.5" />
  </ItemGroup>
</Project>
