<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Net.BITKit.Multiplayer.Contracts</AssemblyName>
    <RootNamespace>BITKit.Multiplayer</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Src/Contracts/**/*.cs" />
  </ItemGroup>
</Project>
