using System;
using System.IO;
using System.Text;
using BITKit.Multiplayer.NetRpc;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.PackageManager;
using UnityEngine;

namespace BITKit.Multiplayer.CodeGen
{
    public static class UnityRemoteInterfaceGenerator
    {
        [DidReloadScripts]
        private static void Reload() => EditorApplication.delayCall += Generate;

        [MenuItem("Tools/BITKit/NetRpc/Generate Remote Interfaces")]
        public static void Generate()
        {
            bool changed = false;
            foreach (var contract in TypeCache.GetTypesWithAttribute<NetRpcRemoteContractAttribute>())
            {
                var attribute = (NetRpcRemoteContractAttribute)Attribute.GetCustomAttribute(contract, typeof(NetRpcRemoteContractAttribute));
                try
                {
                    var path = attribute.OutputAssetPath.Replace('\\', '/');
                    if (path.Contains("..") || Path.IsPathRooted(path) || !path.EndsWith(".cs", StringComparison.Ordinal) || !(path.StartsWith("Assets/", StringComparison.Ordinal) || path.StartsWith("Packages/", StringComparison.Ordinal)))
                        throw new InvalidOperationException("Remote interface output needs a writable Assets/ or local Packages/ .cs path.");
                    string physical;
                    if (path.StartsWith("Packages/", StringComparison.Ordinal))
                    {
                        var package = UnityEditor.PackageManager.PackageInfo.FindForAssetPath(path);
                        if (package == null || package.source != PackageSource.Local && package.source != PackageSource.Embedded) throw new InvalidOperationException("Generated package output must be Local/Embedded.");
                        physical = Path.Combine(package.resolvedPath, path.Substring(package.assetPath.Length + 1));
                    }
                    else physical = Path.GetFullPath(path);
                    var source = "// <auto-generated> NetRpc Unity remote interface. </auto-generated>\n" + RemoteInterfaceSourceGenerator.Generate(contract);
                    if (File.Exists(physical))
                    {
                        var previous = File.ReadAllText(physical);
                        if (previous == source) continue;
                        if (!previous.StartsWith("// <auto-generated> NetRpc Unity remote interface.", StringComparison.Ordinal)) throw new InvalidOperationException("Refusing to overwrite a non-generated source file.");
                    }
                    Directory.CreateDirectory(Path.GetDirectoryName(physical)); File.WriteAllText(physical, source, new UTF8Encoding(false)); changed = true;
                    Debug.Log("NetRpc generated " + contract.FullName + " -> " + path);
                }
                catch (Exception error) { Debug.LogError("NetRpc interface generation: " + contract.FullName + ": " + error.Message); }
            }
            if (changed) AssetDatabase.Refresh();
        }
    }
}
